spring:
  profiles: local
  datasource:
    url: jdbc:log4jdbc:postgresql://192.168.99.101:5432/postgres
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: juhwan
    password: test123
  servlet:
    multipart:
      enabled: true
      location: "./temp"
      max-file-size: 100MB
      max-request-size: 100MB
  devtools:
    restart:
      enabled: false
server:
  port: 3003
logging:
  config: classpath:log4j2_local.yml  
  
mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.bustracker.dto
