spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://mongo:mongo123@localhost:9017
      database: test

  devtools:
    restart:
      enabled: false
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: group-id-test
#      auto-offset-reset: earliest
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 3003
